language: node_js
sudo: required
dist: trusty
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
  - "10"
services:
  - mysql
  - docker
before_script:
  - npm run lint
  - docker run -p 3355:3306 --name mysql:5.5 -e MYSQL_ROOT_PASSWORD=root -d mysql:5.5 --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker run -p 3356:3306 --name mysql:5.6 -e MYSQL_ROOT_PASSWORD=root -d mysql:5.6 --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker run -p 3357:3306 --name mysql:5.7 -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7 --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
  - docker run -p 3357:3306 --name mysql:8.0 -e MYSQL_ROOT_PASSWORD=root -d mysql:5.7 --server-id=1 --log-bin=/var/lib/mysql/mysql-bin.log --binlog-format=row
script:
  - ./test/travis/runner.sh
